version: '3.8'

services:
  genesis-sandbox:
    build:
      context: .
      platforms:
        - "linux/amd64"
    ports:
      - "4242:4242"
    volumes:
      - ./logs:/app/logs
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - GENESIS_BACKEND=cpu
      - GENESIS_LOGGING_LEVEL=debug
      - OPENAI_BASE_URL=http://host.docker.internal:1234/v1/chat/completions
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISPLAY=:99
      - QT_X11_NO_MITSHM=1
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4242/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 